### ISSUE TITLE
Executable's redundant depend suggestion breaks compilation

### ISSUE THREAD

**Issue by pbrisbin** [ndmitchell/weeder#46]
Given this project:

**package.yaml**

```yaml
name: weeder-repro

default-extensions:
  - NoImplicitPrelude

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - text

executables:
  example:
    main: Main.hs
    source-dirs: app
    dependencies:
      - weeder-repro
```

**src/Lib.hs**

```hs
module Lib (main) where

import Prelude

import Data.Text (pack)
import qualified Data.Text.IO as T

main :: IO ()
main = T.putStrLn $ pack "hi"
```

**app/Main.hs**

```hs
module Main
    ( module Lib
    )
where

import Lib (main)
```

Build the project:

```console
stack init
stack setup
stack install --copy-compiler-tool weeder
stack build --test --no-run-tests --bench --no-run-benchmarks
```

Run weeder, observe the following error:

```console
% stack exec weeder 
= Package weeder-repro =

== Section exe:example ==
Redundant build-depends entry
* base

```

This seems reasonable. The exectuable does not in fact use anything from base.

Apply the suggestion:

```yaml
name: weeder-repro

default-extensions:
  - NoImplicitPrelude

library:
  source-dirs: src
  dependencies:
    - base
    - text

executables:
  example:
    main: Main.hs
    source-dirs: app
    dependencies:
      - weeder-repro
```

Build again, and observe it breaks compilation:

```console
% stack build --test --no-run-tests --bench --no-run-benchmarks
weeder-repro-0.0.0: unregistering (local file changes: package.yaml weeder-repro.cabal)
weeder-repro-0.0.0: configure (lib + exe)
Configuring weeder-repro-0.0.0...
weeder-repro-0.0.0: build (lib + exe)
Preprocessing library for weeder-repro-0.0.0..
Building library for weeder-repro-0.0.0..
Preprocessing executable 'example' for weeder-repro-0.0.0..
Building executable 'example' for weeder-repro-0.0.0..
[2 of 2] Compiling Paths_weeder_repro ( .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/example/autogen/Paths_weeder_repro.hs, .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/example/example-tmp/Paths_weeder_repro.o ) [Prelude changed]

/home/patrick/code/pbrisbin/weeder-repro/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/example/autogen/Paths_weeder_repro.hs:10:1: error:
    Could not load module ‘Control.Exception’
    It is a member of the hidden package ‘base-4.12.0.0’.
    Perhaps you need to add ‘base’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
   |
10 | import qualified Control.Exception as Exception
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/patrick/code/pbrisbin/weeder-repro/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/example/autogen/Paths_weeder_repro.hs:11:1: error:
    Could not load module ‘Data.Version’
    It is a member of the hidden package ‘base-4.12.0.0’.
    Perhaps you need to add ‘base’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
   |
11 | import Data.Version (Version(..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/patrick/code/pbrisbin/weeder-repro/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/example/autogen/Paths_weeder_repro.hs:12:1: error:
    Could not load module ‘System.Environment’
    It is a member of the hidden package ‘base-4.12.0.0’.
    Perhaps you need to add ‘base’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
   |
12 | import System.Environment (getEnv)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/patrick/code/pbrisbin/weeder-repro/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/example/autogen/Paths_weeder_repro.hs:13:1: error:
    Could not load module ‘Prelude’
    It is a member of the hidden package ‘base-4.12.0.0’.
    Perhaps you need to add ‘base’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
   |
13 | import Prelude
   | ^^^^^^^^^^^^^^


--  While building package weeder-repro-0.0.0 using:
      /home/patrick/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build lib:weeder-repro exe:example --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

I'm not sure where the fault lies here. Maybe it's unreasonable to expect weeder to be aware of how these `Paths_` modules will be built in a naive hpack-based package?
