### ISSUE TITLE
Non-exhaustive match error on invalid .weeder.yaml

### ISSUE THREAD

**Issue by bergmark** [ndmitchell/weeder#6]
Here's my incorrect yaml, I don't need help finding the error :)

```
package:
  - name: aeson
  - section:
    - name: library
    - message:
      - name: Weeds exported
      - module:
        - name: Data.Aeson.Types.Generic
        - identifier:
        - And
```

**Comment by bergmark** [comment]
Oh, and here's the error message: `weeder: src/Warning.hs:(80,9)-(84,53): Non-exhaustive patterns in function f`

**Comment by bergmark** [comment]
Here's another failure:
```
package:
  - section:
    - name: tests
    - message:
      - name: Weeds exported
      - module:
        - name: Encoders
        - identifier:
          - incoherentInstancesNeededParseJSONString
```

```
weeder: src/Warning.hs:85:9-33: Non-exhaustive patterns in function fromString
```

**Comment by ndmitchell** [comment]
First one now says:

```
*** Exception: Failed to understand Yaml fragment, expected either a dict with 'name' or a list/single string, got
identifier: null
```

It's now total, and always gives an error message saying what it was expecting. Note that you are welcome to delete the `package:` bit entirely, and even the `section:` - I'd probably have written:

```
    - message:
      - name: Weeds exported
      - module:
        - name: Encoders
        - identifier: incoherentInstancesNeededParseJSONString
```
